% Read PDB data generated by Packmol

function pdb = ReadPDB(filename)
fprintf('Reading pdb file: %s\n',filename);
    % Open input file
    f_open=fopen(filename);        % Open .PDB file    
    if f_open==-1
fprintf('\nERROE: Opening pdb file failed!!!\n')
    else
fprintf('\t pdb file opened successfully!\n');
        % Creat intermediate file
        f_inter=fopen('intermediate.text','wt');   % Creat intermediate file
        if f_open~=-1
            % Read inital data from .pdb file, and write into intermediate file. 
            nrow = 0;
            atoms_num=0;
            while ~feof(f_open)
                textl=fgets(f_open);
                nrow = nrow+1;
                if textl(1)=='H'&&textl(2)=='E'&&textl(3)=='T'&&textl(4)=='A'
                    atoms_num=atoms_num+1;
                    for i=13:20
                        fprintf(f_inter,'%s',textl(i));
                    end     
                    for i=27:55
                        fprintf(f_inter,'%s',textl(i));
                    end
                    fprintf(f_inter,'\n');
                end
            end
            fclose(f_open);           % Close input file
            fclose(f_inter);          % Close cache file
            % Read cache file
            f_inter = fopen('intermediate.text');   % Open middata.txt
            % Read 'nrow' row of data, and put them into cell 'c'.
            pdbdata = textscan(f_inter,'%s %s %f %f %f',atoms_num);
            fclose(f_inter);
            % Delete intermediate file
            delete('intermediate.text');
        end
        %%%% Precessing PDB data ==============================================
fprintf('\t >> Processing pdb data...\n');
        mol.typenum = 1;
        mol.types = {};
        mol.type.name{1} = pdbdata{2}(1);
        last_mol = mol.type.name{1};
        molcounter = 0;
        for i=1:size(pdbdata{1})
            if strcmp(pdbdata{2}(i),last_mol)==1
                molcounter = molcounter+1;
            else
                mol.type.num(mol.typenum) = molcounter;
                mol.typenum = mol.typenum+1;
                mol.type.name{mol.typenum} = pdbdata{2}(i);
                last_mol = mol.type.name{mol.typenum};
                molcounter = 1;
            end
            mol.coord(i,1) = pdbdata{3}(i);
            mol.coord(i,2) = pdbdata{4}(i);
            mol.coord(i,3) = pdbdata{5}(i);
        end
        mol.type.num(mol.typenum) = molcounter;
        %%%% ======================= Saving new data ==========================
fprintf('\t >> Saving new data...\n');
        pdb.mols_type = mol.type.name;
        pdb.atoms_num = mol.type.num;
        for i = 1:size(pdb.atoms_num,2)
            if i ==1
                pdb.atoms_coord{i} = mol.coord(1:pdb.atoms_num(i),:);
            else
                pdb.atoms_coord{i} = mol.coord(sum(pdb.atoms_num(1:i-1))+1:sum(pdb.atoms_num(1:i)),:);
            end
        end
fprintf('\t pdb file read successfully!\n');
    end
end